/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    events: Event;
    publications: Publication;
    programs: Program;
    media: Media;
    'team-members': TeamMember;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    events: EventsSelect<false> | EventsSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    programs: ProgramsSelect<false> | ProgramsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    about: About;
    donate: Donate;
    'tax-info': TaxInfo;
    general: General;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    donate: DonateSelect<false> | DonateSelect<true>;
    'tax-info': TaxInfoSelect<false> | TaxInfoSelect<true>;
    general: GeneralSelect<false> | GeneralSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Add upcoming workshops, lectures, and community events. Toggle "Feature on Homepage" to highlight an event.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  date: string;
  endDate?: string | null;
  location?: string | null;
  description?: string | null;
  registrationUrl?: string | null;
  /**
   * Optional link to a dedicated event website, separate from registration.
   */
  websiteUrl?: string | null;
  image?: (number | null) | Media;
  eventType?: ('Workshop' | 'Lecture' | 'Community Event' | 'Conference' | 'Webinar' | 'Other') | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Upload images, PDFs, and other files here. These are used by team member photos, event images, and tax documents.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Add peer-reviewed papers, conference proceedings, and reports. Paste the DOI or PDF link so visitors can access the full paper. Shown on the /press page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: number;
  title: string;
  authors?: string[] | null;
  journal?: string | null;
  year?: number | null;
  abstract?: string | null;
  /**
   * e.g. https://doi.org/10.xxxx/xxxxx or a direct link to the paper
   */
  doi?: string | null;
  pdfUrl?: string | null;
  publicationType?:
    ('Journal Article' | 'Conference Paper' | 'Preprint' | 'Book Chapter' | 'Report' | 'Interview' | 'Other') | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Edit program descriptions shown on the homepage and About page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs".
 */
export interface Program {
  id: number;
  title: string;
  label?: string | null;
  description?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Add, edit, or remove team members. Upload headshots and bios here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  credentials?: string | null;
  role: string;
  memberType: 'current' | 'founding';
  photo?: (number | null) | Media;
  bio?: string | null;
  tags?: string[] | null;
  linkedinUrl?: string | null;
  personalSiteUrl?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'publications';
        value: number | Publication;
      } | null)
    | ({
        relationTo: 'programs';
        value: number | Program;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  endDate?: T;
  location?: T;
  description?: T;
  registrationUrl?: T;
  websiteUrl?: T;
  image?: T;
  eventType?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  title?: T;
  authors?: T;
  journal?: T;
  year?: T;
  abstract?: T;
  doi?: T;
  pdfUrl?: T;
  publicationType?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs_select".
 */
export interface ProgramsSelect<T extends boolean = true> {
  title?: T;
  label?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  credentials?: T;
  role?: T;
  memberType?: T;
  photo?: T;
  bio?: T;
  tags?: T;
  linkedinUrl?: T;
  personalSiteUrl?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Content for the homepage (/).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  /**
   * The large headline at the top of the homepage.
   */
  heroHeadline?: string | null;
  /**
   * Shown in the hero section on the homepage.
   */
  missionStatement?: string | null;
  /**
   * The paragraph above the vision quote in the homepage mission section.
   */
  missionSectionBody?: string | null;
  /**
   * Optional. Replaces the New York skyline in the homepage hero. The sky MUST be cut out and saved as a transparent PNG or WebP — the hero renders its own sky behind this image, so a normal photo will just cover it. Leave empty to use the plate that ships with the site.
   */
  heroSkylinePlate?: (number | null) | Media;
  /**
   * Attribution shown in the corner of the hero.
   */
  heroPhotoCredit?: {
    /**
     * Leave empty to hide the credit entirely.
     */
    text?: string | null;
    url?: string | null;
  };
  /**
   * Which sky the hero opens with. Auto picks sunrise between 5am and 8am, day until 6pm, night after that. Visitors can always switch it themselves, and their choice is remembered.
   */
  heroDefaultLook?: ('auto' | 'night' | 'day' | 'sunrise') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for the About & Mission page (/about).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  /**
   * The paragraph below the vision quote on the About page.
   */
  visionIntro?: string | null;
  /**
   * The official, full mission statement (org description + mission + how we do it) — shown as its own section on the About page.
   */
  missionFull?: string | null;
  /**
   * The "three pillars" cards on the About page.
   */
  pillars?:
    | {
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The "Our History" timeline steps on the About page.
   */
  historyTimeline?:
    | {
        label?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Background image on the About & Mission page.
   */
  aboutHeroImage?: (number | null) | Media;
  /**
   * Image in the BrainWaves program box on the About page. Left blank, the box renders without an image.
   */
  brainwavesImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for the Donate page (/donate).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donate".
 */
export interface Donate {
  id: number;
  /**
   * The large headline at the top of the Donate page.
   */
  donateHeroHeadline?: string | null;
  /**
   * Paste your full donation link here (Every.org, PayPal Giving Fund, Stripe, etc.). This updates the "Donate Now" button across the entire website automatically.
   */
  donationUrl?: string | null;
  /**
   * Shown as a small label on the donate page.
   */
  donationPlatformName?: string | null;
  /**
   * The "Every contribution makes a difference" paragraph on the Donate page.
   */
  donationIntro?: string | null;
  /**
   * The "Where your donation goes" cards on the Donate page.
   */
  impactBlurbs?:
    | {
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Full-width background image on the Donate page.
   */
  donateHeroImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for the Tax Information page (/tax-info).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tax-info".
 */
export interface TaxInfo {
  id: number;
  taxExemptStatus?: string | null;
  fiscalYear?: string | null;
  stateOfIncorporation?: string | null;
  /**
   * Upload official tax documents here. They will appear on the Tax Information page.
   */
  taxDocuments?:
    | {
        label?: string | null;
        year?: number | null;
        file?: (number | null) | Media;
        externalUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The FAQ accordion on the Tax Information page.
   */
  faqItems?:
    | {
        question?: string | null;
        answer?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Settings shared across multiple pages: branding, contact info, and copy that appears on more than one page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general".
 */
export interface General {
  id: number;
  contactEmail?: string | null;
  /**
   * Used in the site header and footer.
   */
  siteLogo?: (number | null) | Media;
  socialLinks?: {
    bluesky?: string | null;
    linkedin?: string | null;
  };
  /**
   * Shown on both the Donate page and the Tax Information page.
   */
  ein?: string | null;
  /**
   * The pulled-quote shown on both the Homepage mission section and the About page vision section.
   */
  visionQuote?: string | null;
  /**
   * The stat blocks (e.g. "30+ / NYC High Schools Reached") shown on both the Homepage and About page.
   */
  orgStats?:
    | {
        value?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Image next to the mission/vision copy on the Home and About pages. Left blank, the section renders without an image.
   */
  missionVisualImage?: (number | null) | Media;
  /**
   * Background image on the Team page.
   */
  teamHeroImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  heroHeadline?: T;
  missionStatement?: T;
  missionSectionBody?: T;
  heroSkylinePlate?: T;
  heroPhotoCredit?:
    | T
    | {
        text?: T;
        url?: T;
      };
  heroDefaultLook?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  visionIntro?: T;
  missionFull?: T;
  pillars?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  historyTimeline?:
    | T
    | {
        label?: T;
        description?: T;
        id?: T;
      };
  aboutHeroImage?: T;
  brainwavesImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donate_select".
 */
export interface DonateSelect<T extends boolean = true> {
  donateHeroHeadline?: T;
  donationUrl?: T;
  donationPlatformName?: T;
  donationIntro?: T;
  impactBlurbs?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  donateHeroImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tax-info_select".
 */
export interface TaxInfoSelect<T extends boolean = true> {
  taxExemptStatus?: T;
  fiscalYear?: T;
  stateOfIncorporation?: T;
  taxDocuments?:
    | T
    | {
        label?: T;
        year?: T;
        file?: T;
        externalUrl?: T;
        id?: T;
      };
  faqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general_select".
 */
export interface GeneralSelect<T extends boolean = true> {
  contactEmail?: T;
  siteLogo?: T;
  socialLinks?:
    | T
    | {
        bluesky?: T;
        linkedin?: T;
      };
  ein?: T;
  visionQuote?: T;
  orgStats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  missionVisualImage?: T;
  teamHeroImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}