import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

// Hand-authored rather than generated by `payload migrate:create`, because
// that command's interactive rename-detection prompt (drizzle-kit) can't run
// non-interactively and there was no safe way to script answers to it. This
// captures every schema change made via dev-mode auto-push since the last
// tracked migration (20260703_194117), verified by introspecting the live
// production database directly:
//   - `events.website_url` column (added for event website links)
//   - `Interview` value on the publications enum (added for the press page)
//   - the single `site_settings` global split into five page-scoped globals
//     (home, about, donate, tax_info, general)
export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "website_url" varchar;
  ALTER TYPE "public"."enum_publications_publication_type" ADD VALUE IF NOT EXISTS 'Interview' BEFORE 'Other';

  DROP TABLE IF EXISTS "site_settings_org_stats";
  DROP TABLE IF EXISTS "site_settings_pillars";
  DROP TABLE IF EXISTS "site_settings_history_timeline";
  DROP TABLE IF EXISTS "site_settings_impact_blurbs";
  DROP TABLE IF EXISTS "site_settings_tax_documents";
  DROP TABLE IF EXISTS "site_settings_faq_items";
  DROP TABLE IF EXISTS "site_settings";

  CREATE TABLE IF NOT EXISTS "home" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"hero_headline" varchar,
  	"mission_statement" varchar,
  	"mission_section_body" varchar,
  	"hero_image_id" integer,
  	"updated_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone
  );

  CREATE TABLE IF NOT EXISTS "about" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"vision_intro" varchar,
  	"mission_full" varchar,
  	"about_hero_image_id" integer,
  	"brainwaves_image_id" integer,
  	"updated_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone
  );

  CREATE TABLE IF NOT EXISTS "about_pillars" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"title" varchar,
  	"description" varchar
  );

  CREATE TABLE IF NOT EXISTS "about_history_timeline" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"label" varchar,
  	"description" varchar
  );

  CREATE TABLE IF NOT EXISTS "donate" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"donate_hero_headline" varchar,
  	"donation_url" varchar,
  	"donation_platform_name" varchar,
  	"donation_intro" varchar,
  	"donate_hero_image_id" integer,
  	"updated_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone
  );

  CREATE TABLE IF NOT EXISTS "donate_impact_blurbs" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"title" varchar,
  	"description" varchar
  );

  CREATE TABLE IF NOT EXISTS "tax_info" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"tax_exempt_status" varchar DEFAULT '501(c)(3) Public Charity',
  	"fiscal_year" varchar DEFAULT 'January 1 – December 31',
  	"state_of_incorporation" varchar DEFAULT 'New York',
  	"updated_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone
  );

  CREATE TABLE IF NOT EXISTS "tax_info_tax_documents" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"label" varchar,
  	"year" numeric,
  	"file_id" integer,
  	"external_url" varchar
  );

  CREATE TABLE IF NOT EXISTS "tax_info_faq_items" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"question" varchar,
  	"answer" varchar
  );

  CREATE TABLE IF NOT EXISTS "general" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"contact_email" varchar DEFAULT 'info@gothamdataclinic.org',
  	"site_logo_id" integer,
  	"social_links_bluesky" varchar,
  	"social_links_linkedin" varchar,
  	"ein" varchar DEFAULT '84-3894797',
  	"vision_quote" varchar,
  	"mission_visual_image_id" integer,
  	"team_hero_image_id" integer,
  	"updated_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone
  );

  CREATE TABLE IF NOT EXISTS "general_org_stats" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"value" varchar,
  	"label" varchar
  );

  DO $$ BEGIN
   ALTER TABLE "home" ADD CONSTRAINT "home_hero_image_id_media_id_fk" FOREIGN KEY ("hero_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null; END $$;
  DO $$ BEGIN
   ALTER TABLE "about" ADD CONSTRAINT "about_about_hero_image_id_media_id_fk" FOREIGN KEY ("about_hero_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null; END $$;
  DO $$ BEGIN
   ALTER TABLE "about" ADD CONSTRAINT "about_brainwaves_image_id_media_id_fk" FOREIGN KEY ("brainwaves_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null; END $$;
  DO $$ BEGIN
   ALTER TABLE "about_pillars" ADD CONSTRAINT "about_pillars_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."about"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null; END $$;
  DO $$ BEGIN
   ALTER TABLE "about_history_timeline" ADD CONSTRAINT "about_history_timeline_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."about"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null; END $$;
  DO $$ BEGIN
   ALTER TABLE "donate" ADD CONSTRAINT "donate_donate_hero_image_id_media_id_fk" FOREIGN KEY ("donate_hero_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null; END $$;
  DO $$ BEGIN
   ALTER TABLE "donate_impact_blurbs" ADD CONSTRAINT "donate_impact_blurbs_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."donate"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null; END $$;
  DO $$ BEGIN
   ALTER TABLE "tax_info_tax_documents" ADD CONSTRAINT "tax_info_tax_documents_file_id_media_id_fk" FOREIGN KEY ("file_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null; END $$;
  DO $$ BEGIN
   ALTER TABLE "tax_info_tax_documents" ADD CONSTRAINT "tax_info_tax_documents_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."tax_info"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null; END $$;
  DO $$ BEGIN
   ALTER TABLE "tax_info_faq_items" ADD CONSTRAINT "tax_info_faq_items_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."tax_info"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null; END $$;
  DO $$ BEGIN
   ALTER TABLE "general" ADD CONSTRAINT "general_site_logo_id_media_id_fk" FOREIGN KEY ("site_logo_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null; END $$;
  DO $$ BEGIN
   ALTER TABLE "general" ADD CONSTRAINT "general_mission_visual_image_id_media_id_fk" FOREIGN KEY ("mission_visual_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null; END $$;
  DO $$ BEGIN
   ALTER TABLE "general" ADD CONSTRAINT "general_team_hero_image_id_media_id_fk" FOREIGN KEY ("team_hero_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null; END $$;
  DO $$ BEGIN
   ALTER TABLE "general_org_stats" ADD CONSTRAINT "general_org_stats_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."general"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null; END $$;

  CREATE INDEX IF NOT EXISTS "home_hero_image_idx" ON "home" USING btree ("hero_image_id");
  CREATE INDEX IF NOT EXISTS "about_about_hero_image_idx" ON "about" USING btree ("about_hero_image_id");
  CREATE INDEX IF NOT EXISTS "about_brainwaves_image_idx" ON "about" USING btree ("brainwaves_image_id");
  CREATE INDEX IF NOT EXISTS "about_pillars_order_idx" ON "about_pillars" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "about_pillars_parent_id_idx" ON "about_pillars" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "about_history_timeline_order_idx" ON "about_history_timeline" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "about_history_timeline_parent_id_idx" ON "about_history_timeline" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "donate_donate_hero_image_idx" ON "donate" USING btree ("donate_hero_image_id");
  CREATE INDEX IF NOT EXISTS "donate_impact_blurbs_order_idx" ON "donate_impact_blurbs" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "donate_impact_blurbs_parent_id_idx" ON "donate_impact_blurbs" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "tax_info_tax_documents_file_idx" ON "tax_info_tax_documents" USING btree ("file_id");
  CREATE INDEX IF NOT EXISTS "tax_info_tax_documents_order_idx" ON "tax_info_tax_documents" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "tax_info_tax_documents_parent_id_idx" ON "tax_info_tax_documents" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "tax_info_faq_items_order_idx" ON "tax_info_faq_items" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "tax_info_faq_items_parent_id_idx" ON "tax_info_faq_items" USING btree ("_parent_id");
  CREATE INDEX IF NOT EXISTS "general_site_logo_idx" ON "general" USING btree ("site_logo_id");
  CREATE INDEX IF NOT EXISTS "general_mission_visual_image_idx" ON "general" USING btree ("mission_visual_image_id");
  CREATE INDEX IF NOT EXISTS "general_team_hero_image_idx" ON "general" USING btree ("team_hero_image_id");
  CREATE INDEX IF NOT EXISTS "general_org_stats_order_idx" ON "general_org_stats" USING btree ("_order");
  CREATE INDEX IF NOT EXISTS "general_org_stats_parent_id_idx" ON "general_org_stats" USING btree ("_parent_id");
  `)
}

// Note: Postgres can't remove an enum value once added, so `Interview` on
// enum_publications_publication_type isn't reverted here. The old
// site_settings* tables also aren't recreated — this migration retires them
// for good rather than making them restorable.
export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   DROP TABLE IF EXISTS "general_org_stats";
  DROP TABLE IF EXISTS "general";
  DROP TABLE IF EXISTS "tax_info_faq_items";
  DROP TABLE IF EXISTS "tax_info_tax_documents";
  DROP TABLE IF EXISTS "tax_info";
  DROP TABLE IF EXISTS "donate_impact_blurbs";
  DROP TABLE IF EXISTS "donate";
  DROP TABLE IF EXISTS "about_history_timeline";
  DROP TABLE IF EXISTS "about_pillars";
  DROP TABLE IF EXISTS "about";
  DROP TABLE IF EXISTS "home";
  ALTER TABLE "events" DROP COLUMN IF EXISTS "website_url";
  `)
}
